"""Added tab column

Revision ID: d9af8d726675
Revises: 
Create Date: 2025-07-15 03:39:15.280043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9af8d726675'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tab', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('company_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('project_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('linked_in', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('resume_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('referral', sa.String(length=50), nullable=True))
        batch_op.drop_column('message')
        batch_op.drop_column('subject')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('subject', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('message', sa.TEXT(), nullable=True))
        batch_op.drop_column('referral')
        batch_op.drop_column('resume_filename')
        batch_op.drop_column('linked_in')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('project_details')
        batch_op.drop_column('phone')
        batch_op.drop_column('company_email')
        batch_op.drop_column('tab')

    # ### end Alembic commands ###
